teams_east = [
    "BOS",
    "NYK",
    "MIL",
    "CLE",
    "ORL",
    "IND",
    "PHI",
    "MIA",
    "CHI",
    "ATL",
    "BRK",
    "TOR",
    "CHO",
    "WAS",
    "DET"
]

teams_west = [
    "OKC",
    "DEN",
    "MIN",
    "LAC",
    "DAL",
    "PHO",
    "NOP",
    "LAL",
    "SAC",
    "GSW",
    "HOU",
    "UTA",
    "MEM",
    "SAS",
    "POR"
]

players = [
    "curryst01",
    "antetgi01",
    "jamesle01",
    "doncilu01",
    "jokicni01",
    "gilgesh01",
    "embiijo01",
    "duranke01",
    "irvinky01",
    "edwaran01",
    "georgpa01",
    "bookede01",
    "willizi01",
    "tatumja01",
    "brunsja01",
    "butleji01",
    "goberru01",
    "wembavi01",
    "derozde01",
    "youngtr01",
    "hardeja01",
    "thompkl01"
]


players_dict = {
    "curryst01": "Stephen Curry",
    "antetgi01": "Giannis Antetokounmpo",
    "jamesle01": "LeBron James",
    "doncilu01": "Luka Doncic",
    "jokicni01": "Nikola Jokic",
    "gilgesh01": "Shai Gilgeous-Alexander",
    "embiijo01": "Joel Embiid",
    "duranke01": "Kevin Durant",
    "irvinky01": "Kyrie Irving",
    "edwaran01": "Anthony Edwards",
    "georgpa01": "Paul George",
    "bookede01": "Devin Booker",
    "willizi01": "Zion Williamson",
    "tatumja01": "Jayson Tatum",
    "brunsja01": "Jalen Brunson",
    "butleji01": "Jimmy Butler",
    "goberru01": "Rudy Gobert",
    "wembavi01": "Victor Wembanyama",
    "derozde01": "DeMar DeRozan",
    "youngtr01": "Trae Young",
    "hardeja01": "James Harden",
    "thompkl01": "Klay Thompson"
}

teams_dict = {
    "BOS": "Boston Celtics",
    "NYK": "New York Knicks",
    "MIL": "Milwaukee Bucks",
    "CLE": "Cleveland Cavaliers",
    "ORL": "Orlando Magic",
    "IND": "Indiana Pacers",
    "PHI": "Philadelphia 76ers",
    "MIA": "Miami Heat",
    "CHI": "Chicago Bulls",
    "ATL": "Atlanta Hawks",
    "BRK": "Brooklyn Nets",
    "TOR": "Toronto Raptors",
    "CHO": "Charlotte Hornets",
    "WAS": "Washington Wizards",
    "DET": "Detroit Pistons",
    "OKC": "Oklahoma City Thunder",
    "DEN": "Denver Nuggets",
    "MIN": "Minnesota Timberwolves",
    "LAC": "Los Angeles Clippers",
    "DAL": "Dallas Mavericks",
    "PHO": "Phoenix Suns",
    "NOP": "New Orleans Pelicans",
    "LAL": "Los Angeles Lakers",
    "SAC": "Sacremento Kings",
    "GSW": "Golden State Warriors",
    "HOU": "Houston Rockets",
    "UTA": "Utah Jazz",
    "MEM": "Memphis Grizzlies",
    "SAS": "San Antonio Spurs",
    "POR": "Portland Trailblazers"
}
